spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oldhealth?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: wang.123
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  redis:
    host: 39.106.19.162
    port: 6379
    password: wang.123